CREATE DATABASE IF NOT EXISTS HAMBURGUER;

USE HAMBURGUER;

CREATE TABLE IF NOT EXISTS TB_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NM_USUARIO VARCHAR(200) NOT NULL,
    DS_EMAIL VARCHAR(200) NOT NULL UNIQUE,
    DS_SENHA_HASH VARCHAR(200) NOT NULL 
);

CREATE TABLE PRODUTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(1000),
    PRECO DECIMAL(10, 2) NOT NULL,
    CATEGORIA VARCHAR(50),
    DISPONIVEL BOOLEAN NOT NULL DEFAULT TRUE,
    BEBIDA BOOLEAN NOT NULL DEFAULT FALSE,
    VEGANO BOOLEAN NOT NULL DEFAULT FALSE,
    TIPO_FRANGO BOOLEAN NOT NULL DEFAULT FALSE,
    TIPO_CARNE BOOLEAN NOT NULL DEFAULT FALSE,
    INGREDIENTES VARCHAR(1000)
);